---
extends:
  - eslint:recommended
  - airbnb-base
  - prettier

plugins:
  - import
  - notice

rules:
  no-plusplus: 'off'
  no-case-declarations: 'off'
  class-methods-use-this: 'off'
  no-continue: 'off'
  no-nested-ternary: 'off'
  prefer-destructuring: 'off'
  no-param-reassign: 'off'
  no-use-before-define:
    - error
    - functions: false
      classes: true
  no-restricted-syntax: 'off'
  guard-for-in: 'off'

  no-invalid-this: error
  no-new-wrappers: error
  no-underscore-dangle: 'off'

  import/no-deprecated: 1
  import/order:
    - error
    - newlines-between: always
  import/extensions:
    - error
    - ignorePackages
    - js: never
      mjs: never
      ts: never
  import/prefer-default-export: 'off'

  notice/notice:
    - error
    - mustMatch: Copyright \(c\) \d{4}
      template: |
        /**
         * Copyright (c) <%= YEAR %> Adrian Panella <ianchi74@outlook.com>
         * This software is released under the MIT License.
         * https://opensource.org/licenses/MIT
         */

overrides:
  - files: '*.ts'
    extends:
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/recommended-requiring-type-checking
      - prettier
      - plugin:import/typescript

    parserOptions:
      project:
        - tsconfig.json
        - ./spec/tsconfig.json

    rules:
      '@typescript-eslint/array-type':
        - error
        - default: array-simple
      # '@typescript-eslint/camelcase': 'off'
      # '@typescript-eslint/consistent-type-assertions': 'off'
      '@typescript-eslint/consistent-type-definitions':
        - error
        - interface
      #'@typescript-eslint/explicit-function-return-type': 'off'
      '@typescript-eslint/explicit-member-accessibility':
        - error
        - accessibility: no-public
      # '@typescript-eslint/interface-name-prefix': 'off'
      # '@typescript-eslint/member-ordering': 'off'
      '@typescript-eslint/naming-convention':
        - error
        - selector: class
          format:
            - PascalCase

      '@typescript-eslint/no-inferrable-types': error
      '@typescript-eslint/no-misused-new': error
      '@typescript-eslint/no-require-imports': error
      '@typescript-eslint/no-unused-vars':
        - error
        - argsIgnorePattern: ^_
      '@typescript-eslint/no-use-before-define':
        - error
        - functions: false
      '@typescript-eslint/prefer-function-type': error
      '@typescript-eslint/unified-signatures': error

      # revert recommended as rework is needed to remove 'any'
      '@typescript-eslint/no-explicit-any': 'off'
      '@typescript-eslint/no-non-null-assertion': 'off'
      '@typescript-eslint/no-unsafe-assignment': 'off'
      '@typescript-eslint/no-unsafe-call': 'off'
      '@typescript-eslint/no-unsafe-member-access': 'off'
      '@typescript-eslint/no-unsafe-return': 'off'
